services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: slbp
      MYSQL_PASSWORD: slbp
      MYSQL_DATABASE: slbp
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10


